# Generated by Django 4.2.2 on 2023-07-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='available_from',
            field=models.DateTimeField(blank=True, null=True, verbose_name='available from'),
        ),
        migrations.AddField(
            model_name='question',
            name='available_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='available until'),
        ),
    ]
